app: matrix-cloud
service: <no value>
ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 9090
    targetPort: 9090
    name: grpc
metrics:
  scrape: false
  path: /metrics/prometheus
hpa: true
